export const NAVIGATION_ROUTES = {
    // AUTH SIDE ROUTES
    SPLASHSCREEN: 'SPLASHSCREEN',
    ONBOARDING: 'ONBOARDING',
    SIGNUP:'SIGNUP',
    DASHBOARD:'DASHBOARD',
    EDITSCREEN:'EDITSCREEN'
  };
  